In [1]:
import pandas as pd
import numpy as np

In [20]:
crime_anal=pd.read_csv('../data/crime_anal_in_Seoul.csv',encoding='euc-kr',index_col='구별')
crime_anal.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,0.0,25.0,12.0,2372.0,3159.0,NaN,92.000000,91.666667,48.903879,87.021209
강동구,0.0,6.0,3.0,1612.0,1713.0,NaN,100.000000,100.000000,55.148883,85.288967
강북구,0.0,1.0,4.0,777.0,1383.0,NaN,100.000000,100.000000,69.111969,90.744758
강서구,0.0,3.0,9.0,1540.0,2098.0,NaN,100.000000,77.777778,59.805195,91.754051
관악구,0.0,7.0,8.0,1860.0,2248.0,NaN,85.714286,50.000000,49.946237,85.676157

In [3]:
from sklearn import preprocessing

In [21]:
col=['강간','강도','살인','절도','폭력']

x=crime_anal[col].values
min_max_scaler=preprocessing.MinMaxScaler()

x_scaled=min_max_scaler.fit_transform(x.astype(float))
crime_anal_norm=pd.DataFrame(x_scaled, columns=col, index=crime_anal.index)

col2=['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']
crime_anal_norm[col2]=crime_anal[col2]

crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,0.0,1.000000,1.000000,1.000000,1.000000,NaN,92.000000,91.666667,48.903879,87.021209
강동구,0.0,0.208333,0.181818,0.525000,0.326502,NaN,100.000000,100.000000,55.148883,85.288967
강북구,0.0,0.000000,0.272727,0.003125,0.172799,NaN,100.000000,100.000000,69.111969,90.744758
강서구,0.0,0.083333,0.727273,0.480000,0.505822,NaN,100.000000,77.777778,59.805195,91.754051
관악구,0.0,0.250000,0.636364,0.680000,0.575687,NaN,85.714286,50.000000,49.946237,85.676157

In [22]:
result_CCTV=pd.read_csv('../data/CCTV_result.csv',encoding='euc-kr',index_col='구별')

In [23]:
result_CCTV.head()

      CCTV수     인구수     한국인  등록외국인  65세이상고령자     외국인비율
구별
종로구    1715  153684  144275   9409     28064  6.122303
용산구    2611  236518  222169  14349     39461  6.066769
성동구    3829  291609  285073   6536     46896  2.241357
광진구    3211  353110  340707  12403     52604  3.512503
동대문구   2628  352592  337982  14610     62963  4.143599

In [25]:
crime_anal_norm[['인구수','CCTV']]=result_CCTV[['인구수','CCTV수']]
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV
구별,,,,,,,,,,,,
강남구,0.0,1.000000,1.000000,1.000000,1.000000,NaN,92.000000,91.666667,48.903879,87.021209,537338.0,6871.0
강동구,0.0,0.208333,0.181818,0.525000,0.326502,NaN,100.000000,100.000000,55.148883,85.288967,465097.0,2809.0
강북구,0.0,0.000000,0.272727,0.003125,0.172799,NaN,100.000000,100.000000,69.111969,90.744758,300824.0,3090.0
강서구,0.0,0.083333,0.727273,0.480000,0.505822,NaN,100.000000,77.777778,59.805195,91.754051,578426.0,2744.0
관악구,0.0,0.250000,0.636364,0.680000,0.575687,NaN,85.714286,50.000000,49.946237,85.676157,500336.0,5149.0

In [26]:
col=['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']
crime_anal_norm['검거']=np.sum(crime_anal_norm[col],axis=1)
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,검거
구별,,,,,,,,,,,,,
강남구,0.0,1.000000,1.000000,1.000000,1.000000,NaN,92.000000,91.666667,48.903879,87.021209,537338.0,6871.0,319.591754
강동구,0.0,0.208333,0.181818,0.525000,0.326502,NaN,100.000000,100.000000,55.148883,85.288967,465097.0,2809.0,340.437850
강북구,0.0,0.000000,0.272727,0.003125,0.172799,NaN,100.000000,100.000000,69.111969,90.744758,300824.0,3090.0,359.856727
강서구,0.0,0.083333,0.727273,0.480000,0.505822,NaN,100.000000,77.777778,59.805195,91.754051,578426.0,2744.0,329.337024
관악구,0.0,0.250000,0.636364,0.680000,0.575687,NaN,85.714286,50.000000,49.946237,85.676157,500336.0,5149.0,271.336679

In [27]:
col=['강간','강도','살인','절도','폭력']
crime_anal_norm['범죄']=np.sum(crime_anal_norm[col],axis=1)
crime_anal_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,검거,범죄
구별,,,,,,,,,,,,,,
강남구,0.0,1.000000,1.000000,1.000000,1.000000,NaN,92.000000,91.666667,48.903879,87.021209,537338.0,6871.0,319.591754,4.000000
강동구,0.0,0.208333,0.181818,0.525000,0.326502,NaN,100.000000,100.000000,55.148883,85.288967,465097.0,2809.0,340.437850,1.241654
강북구,0.0,0.000000,0.272727,0.003125,0.172799,NaN,100.000000,100.000000,69.111969,90.744758,300824.0,3090.0,359.856727,0.448652
강서구,0.0,0.083333,0.727273,0.480000,0.505822,NaN,100.000000,77.777778,59.805195,91.754051,578426.0,2744.0,329.337024,1.796428
관악구,0.0,0.250000,0.636364,0.680000,0.575687,NaN,85.714286,50.000000,49.946237,85.676157,500336.0,5149.0,271.336679,2.142051

In [28]:
crime_anal_norm.to_csv('../data/crime_anal_norm_in_Seoul.csv',sep=',',encoding='euc-kr')