In [2]:
import pandas as pd
import numpy as np

In [6]:
crime_and_raw=pd.read_csv('../data/crime_in_Seoul_include_gu_name.csv',encoding='euc-kr',index_col=0)

In [7]:
crime_and_raw.head()

,관서명,강간 검거,강간 발생,"강간,추행 검거","강간,추행 발생",강도 검거,강도 발생,살인 검거,살인 발생,절도 검거,절도 발생,폭력 검거,폭력 발생,구별
0,강남,NaN,NaN,325.0,428.0,11.0,13.0,6.0,8.0,737.0,1517.0,1699.0,1961.0,강남구
1,강동,NaN,NaN,103.0,124.0,6.0,6.0,3.0,3.0,889.0,1612.0,1461.0,1713.0,강동구
2,강북,NaN,NaN,115.0,136.0,1.0,1.0,4.0,4.0,537.0,777.0,1255.0,1383.0,강북구
3,강서,NaN,NaN,188.0,246.0,3.0,3.0,7.0,9.0,921.0,1540.0,1925.0,2098.0,강서구
4,관악,NaN,NaN,269.0,321.0,6.0,7.0,4.0,8.0,929.0,1860.0,1926.0,2248.0,관악구

In [8]:
crime_anal=pd.pivot_table(crime_and_raw, index='구별', aggfunc=np.sum)

In [9]:
crime_anal.head()

,강간 검거,강간 발생,"강간,추행 검거","강간,추행 발생",강도 검거,강도 발생,살인 검거,살인 발생,절도 검거,절도 발생,폭력 검거,폭력 발생
구별,,,,,,,,,,,,
강남구,0.0,0.0,454.0,578.0,23.0,25.0,11.0,12.0,1160.0,2372.0,2749.0,3159.0
강동구,0.0,0.0,103.0,124.0,6.0,6.0,3.0,3.0,889.0,1612.0,1461.0,1713.0
강북구,0.0,0.0,115.0,136.0,1.0,1.0,4.0,4.0,537.0,777.0,1255.0,1383.0
강서구,0.0,0.0,188.0,246.0,3.0,3.0,7.0,9.0,921.0,1540.0,1925.0,2098.0
관악구,0.0,0.0,269.0,321.0,6.0,7.0,4.0,8.0,929.0,1860.0,1926.0,2248.0

In [10]:
del crime_anal['강간,추행 검거']
del crime_anal['강간,추행 발생']
crime_anal.head()

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생   절도 검거   절도 발생   폭력 검거   폭력 발생
구별
강남구    0.0    0.0   23.0   25.0   11.0   12.0  1160.0  2372.0  2749.0  3159.0
강동구    0.0    0.0    6.0    6.0    3.0    3.0   889.0  1612.0  1461.0  1713.0
강북구    0.0    0.0    1.0    1.0    4.0    4.0   537.0   777.0  1255.0  1383.0
강서구    0.0    0.0    3.0    3.0    7.0    9.0   921.0  1540.0  1925.0  2098.0
관악구    0.0    0.0    6.0    7.0    4.0    8.0   929.0  1860.0  1926.0  2248.0

In [11]:
crime_anal['강간검거율']=crime_anal['강간 검거']/crime_anal['강간 발생']*100
crime_anal['강도검거율']=crime_anal['강도 검거']/crime_anal['강도 발생']*100
crime_anal['살인검거율']=crime_anal['살인 검거']/crime_anal['살인 발생']*100
crime_anal['절도검거율']=crime_anal['절도 검거']/crime_anal['절도 발생']*100
crime_anal['폭력검거율']=crime_anal['폭력 검거']/crime_anal['폭력 발생']*100

del crime_anal['강간 검거']
del crime_anal['강도 검거']
del crime_anal['살인 검거']
del crime_anal['절도 검거']
del crime_anal['폭력 검거']

crime_anal.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,0.0,25.0,12.0,2372.0,3159.0,NaN,92.000000,91.666667,48.903879,87.021209
강동구,0.0,6.0,3.0,1612.0,1713.0,NaN,100.000000,100.000000,55.148883,85.288967
강북구,0.0,1.0,4.0,777.0,1383.0,NaN,100.000000,100.000000,69.111969,90.744758
강서구,0.0,3.0,9.0,1540.0,2098.0,NaN,100.000000,77.777778,59.805195,91.754051
관악구,0.0,7.0,8.0,1860.0,2248.0,NaN,85.714286,50.000000,49.946237,85.676157

In [12]:
crime_anal

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,0.0,25.0,12.0,2372.0,3159.0,NaN,92.000000,91.666667,48.903879,87.021209
강동구,0.0,6.0,3.0,1612.0,1713.0,NaN,100.000000,100.000000,55.148883,85.288967
강북구,0.0,1.0,4.0,777.0,1383.0,NaN,100.000000,100.000000,69.111969,90.744758
강서구,0.0,3.0,9.0,1540.0,2098.0,NaN,100.000000,77.777778,59.805195,91.754051
관악구,0.0,7.0,8.0,1860.0,2248.0,NaN,85.714286,50.000000,49.946237,85.676157
광진구,0.0,4.0,5.0,1414.0,1456.0,NaN,100.000000,60.000000,53.323904,87.912088
구로구,0.0,2.0,5.0,1390.0,1907.0,NaN,50.000000,100.000000,55.395683,80.597798
금천구,0.0,3.0,7.0,1013.0,1282.0,NaN,133.333333,85.714286,51.332675,86.427457
노원구,0.0,3.0,6.0,1361.0,1899.0,NaN,100.000000,100.000000,48.052902,79.673512
도봉구,72.0,2.0,2.0,772.0,1012.0,88.888889,50.000000,100.000000,48.704663,84.090909
동대문구,0.0,7.0,3.0,1240.0,1540.0,NaN,114.285714,133.333333,53.145161,84.090909
동작구,0.0,1.0,2.0,1129.0,1319.0,NaN,100.000000,150.000000,59.787422,80.060652
마포구,0.0,4.0,4.0,1510.0,1701.0,NaN,100.000000,75.000000,48.344371,80.364491
서대문구,0.0,2.0,3.0,1027.0,1109.0,NaN,100.000000,100.000000,54.722493,81.785392
서초구,47.0,5.0,9.0,1503.0,1827.0,78.723404,100.000000,100.000000,45.974717,82.430213
성동구,0.0,4.0,3.0,905.0,1090.0,NaN,25.000000,133.333333,54.917127,84.954128
성북구,118.0,2.0,4.0,895.0,1392.0,74.576271,100.000000,75.000000,52.960894,87.643678
송파구,0.0,7.0,3.0,2024.0,2433.0,NaN,85.714286,100.000000,49.160079,84.093711
양천구,116.0,3.0,1.0,1349.0,1546.0,79.310345,100.000000,100.000000,51.890289,83.376455
영등포구,0.0,11.0,8.0,1712.0,2169.0,NaN,100.000000,100.000000,48.539720,79.806362
용산구,0.0,1.0,3.0,945.0,1291.0,NaN,100.000000,66.666667,51.216931,82.804028
은평구,0.0,3.0,4.0,1424.0,1647.0,NaN,100.000000,125.000000,57.935393,88.463874
종로구,0.0,4.0,6.0,1079.0,1467.0,NaN,100.000000,50.000000,46.709917,80.981595
중구,0.0,6.0,6.0,1279.0,1409.0,NaN,100.000000,100.000000,57.779515,86.870121
중랑구,0.0,6.0,4.0,1399.0,1660.0,NaN,116.666667,100.000000,59.685490,86.867470

In [16]:
con_list=['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']

for column in con_list:
    crime_anal.loc[crime_anal[column]>100, column]=100
    
crime_anal

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,0.0,25.0,12.0,2372.0,3159.0,NaN,92.000000,91.666667,48.903879,87.021209
강동구,0.0,6.0,3.0,1612.0,1713.0,NaN,100.000000,100.000000,55.148883,85.288967
강북구,0.0,1.0,4.0,777.0,1383.0,NaN,100.000000,100.000000,69.111969,90.744758
강서구,0.0,3.0,9.0,1540.0,2098.0,NaN,100.000000,77.777778,59.805195,91.754051
관악구,0.0,7.0,8.0,1860.0,2248.0,NaN,85.714286,50.000000,49.946237,85.676157
광진구,0.0,4.0,5.0,1414.0,1456.0,NaN,100.000000,60.000000,53.323904,87.912088
구로구,0.0,2.0,5.0,1390.0,1907.0,NaN,50.000000,100.000000,55.395683,80.597798
금천구,0.0,3.0,7.0,1013.0,1282.0,NaN,100.000000,85.714286,51.332675,86.427457
노원구,0.0,3.0,6.0,1361.0,1899.0,NaN,100.000000,100.000000,48.052902,79.673512
도봉구,72.0,2.0,2.0,772.0,1012.0,88.888889,50.000000,100.000000,48.704663,84.090909
동대문구,0.0,7.0,3.0,1240.0,1540.0,NaN,100.000000,100.000000,53.145161,84.090909
동작구,0.0,1.0,2.0,1129.0,1319.0,NaN,100.000000,100.000000,59.787422,80.060652
마포구,0.0,4.0,4.0,1510.0,1701.0,NaN,100.000000,75.000000,48.344371,80.364491
서대문구,0.0,2.0,3.0,1027.0,1109.0,NaN,100.000000,100.000000,54.722493,81.785392
서초구,47.0,5.0,9.0,1503.0,1827.0,78.723404,100.000000,100.000000,45.974717,82.430213
성동구,0.0,4.0,3.0,905.0,1090.0,NaN,25.000000,100.000000,54.917127,84.954128
성북구,118.0,2.0,4.0,895.0,1392.0,74.576271,100.000000,75.000000,52.960894,87.643678
송파구,0.0,7.0,3.0,2024.0,2433.0,NaN,85.714286,100.000000,49.160079,84.093711
양천구,116.0,3.0,1.0,1349.0,1546.0,79.310345,100.000000,100.000000,51.890289,83.376455
영등포구,0.0,11.0,8.0,1712.0,2169.0,NaN,100.000000,100.000000,48.539720,79.806362
용산구,0.0,1.0,3.0,945.0,1291.0,NaN,100.000000,66.666667,51.216931,82.804028
은평구,0.0,3.0,4.0,1424.0,1647.0,NaN,100.000000,100.000000,57.935393,88.463874
종로구,0.0,4.0,6.0,1079.0,1467.0,NaN,100.000000,50.000000,46.709917,80.981595
중구,0.0,6.0,6.0,1279.0,1409.0,NaN,100.000000,100.000000,57.779515,86.870121
중랑구,0.0,6.0,4.0,1399.0,1660.0,NaN,100.000000,100.000000,59.685490,86.867470

In [19]:
crime_anal.rename(columns={'강간 발생':'강간',
                          '강도 발생':'강도',
                          '살인 발생':'살인',
                          '절도 발생':'절도',
                          '폭력 발생':'폭력'},inplace=True)
crime_anal.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,0.0,25.0,12.0,2372.0,3159.0,NaN,92.000000,91.666667,48.903879,87.021209
강동구,0.0,6.0,3.0,1612.0,1713.0,NaN,100.000000,100.000000,55.148883,85.288967
강북구,0.0,1.0,4.0,777.0,1383.0,NaN,100.000000,100.000000,69.111969,90.744758
강서구,0.0,3.0,9.0,1540.0,2098.0,NaN,100.000000,77.777778,59.805195,91.754051
관악구,0.0,7.0,8.0,1860.0,2248.0,NaN,85.714286,50.000000,49.946237,85.676157

In [22]:
crime_anal.to_csv('../data/crime_anal_in_Seoul.csv', sep=',', encoding='euc-kr')